name: CI-CD

on:
  workflow_dispatch:        # habilita o botão "Run workflow" na aba Actions
  push:
    branches: ["main"]      # mantém o trigger automático por push

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build & Push da imagem
        uses: docker/build-push-action@v5
        with:
          context: ./kube-news/src
          file: ./kube-news/src/Dockerfile
          push: true
          tags: |
            devopsdangluglu/live-kube-news:${{ github.run_number }}
            devopsdangluglu/live-kube-news:latest
